# Build.tf

locals {
  project_dir = (var.infra_as_code=="from_resource_manager")?".":"../.."
}

# SSH Keys + tf_env.sh
resource "null_resource" "tf_env" {
  provisioner "local-exec" {
    command = <<-EOT
    cd ${local.project_dir}
    mkdir -p target
    # Create the files needed by the shell scripts
    # Create SSH Key
    echo "${local.ssh_public_key}" > target/ssh_key_starter.pub
    echo "${local.ssh_private_key}" > target/ssh_key_starter
    chmod 600 target/ssh_key_starter.pub
    chmod 600 target/ssh_key_starter
    
    # Create target/tf_env.sh
    ENV_FILE=target/tf_env.sh
    echo "# Generated by terraform - build.tf" > $ENV_FILE
    echo "" >> $ENV_FILE
    echo "# Terraform Variables" >> $ENV_FILE
    append() {
      echo "$1" >> $ENV_FILE
    }    
    append_export() {
      if [ "$2" != "" ] && [ "$2" != "-" ]; then
        echo "export $1=\"$2\"" >> $ENV_FILE
      fi 
    }
    append_export "TF_VAR_prefix" "${coalesce(var.prefix,"-")}"
    append_export "TF_VAR_db_password" "${coalesce(var.db_password,"-")}"
    append_export "TF_VAR_license_model" "${coalesce(var.license_model,"-")}"
    append_export "TF_VAR_your_public_ssh_key" "${coalesce(var.your_public_ssh_key,"-")}"
    append_export "TF_VAR_compartment_ocid" "${coalesce(var.compartment_ocid,"-")}"  
    append "# Terraform Locals"
    append_export "BASTION_IP" "${local.local_bastion_ip}"
    append_export "COMPUTE_IP" "${local.local_compute_ip}"
    append_export "DB_URL" "${local.local_db_url}"
    append_export "IDCS_URL" "${local.local_idcs_url}"
    append_export "JDBC_URL" "${local.local_jdbc_url}"
    append_export "OBJECT_STORAGE_NAMESPACE" "${local.local_object_storage_namespace}"
    append_export "OCIR_HOST" "${local.local_ocir_host}"
    append_export "ORDS_URL" "${local.local_ords_url}" 
    append "# Fixed"
    append_export "TF_VAR_app_mode" "terraform"
    append_export "TF_VAR_build_host" "bastion"
    append_export "TF_VAR_db_type" "autonomous"
    append_export "TF_VAR_db_user" "admin"
    append_export "TF_VAR_deploy_type" "public_compute"
    append_export "TF_VAR_language" "python"
    append_export "TF_VAR_python_framework" "langgraph"
    append_export "TF_VAR_ui_type" "langgraph"
    append "# Region"   
    append "curl -s -H 'Authorization: Bearer Oracle' -L http://169.254.169.254/opc/v2/instance/ > /tmp/instance.json"   
    append 'export TF_VAR_region="${local.current_region_name}"'
 
    append "# Database"
    append "export DB_USER=\$TF_VAR_db_user" 
    append "export DB_PASSWORD=\$TF_VAR_db_password" 
    # append_export "OCI_STARTER_CREATION_DATE" "2026-05-04-07-43-42-047484"
    # append_export "OCI_STARTER_VERSION" "4.2"
    # append_export "OCI_STARTER_PARAMS" "prefix,java_framework,java_vm,java_version,python_framework,ui_type,db_type,license_model,app_mode,mode,infra_as_code,db_password,oke_type,security,build_host,deploy_type,language"
    chmod 755 $ENV_FILE
    EOT
  }
  triggers = {
    always_run = "${timestamp()}"
  }     
}

## BUILD_DEPLOY
resource "null_resource" "build_deploy" {
  provisioner "local-exec" {
    command = <<-EOT
        cd ${local.project_dir}
        export CALLED_BY_TERRAFORM="true"
        . ./starter.sh env        
        # pwd
        # ls -al target
        # cat target/terraform.tfstate
        # export
        # Run config command on the DB directly (ex RAC)

        # Init target/compute
        if is_deploy_compute; then
            mkdir -p target/compute
            cp -r bin/compute target/compute/.
        elif [ "$TF_VAR_deploy_type" == "kubernetes" ]; then
            $BIN_DIR/config_oke.sh
            exit_on_error "Deploy $TF_VAR_deploy_type"        
        fi

        # Build all apps
        if [ "$TF_VAR_build_host" == "terraform" ]; then
            for APP_NAME in `app_name_list_build`; do
                src/app/$APP_NAME/build.sh
                exit_on_error "Build App $APP_NAME"
            done
        fi 

        # Build the DB tables (via Bastion)
        if [ -d src/app/db ] || [ "$TF_VAR_deploy_type" == "public_compute" ]; then
            title "Deploy Bastion"
            $BIN_DIR/deploy_bastion.sh
            exit_on_error "Deploy Bastion"   
        fi  

        # Deploy
        title "Deploy $TF_VAR_deploy_type"
        if [ "$TF_VAR_deploy_type" == "public_compute" ]; then
            echo "Skipping. Done via Deploy Bastion."
        elif [ "$TF_VAR_deploy_type" == "private_compute" ] || [ "$TF_VAR_deploy_type" == "instance_pool" ]; then
            $BIN_DIR/deploy_compute.sh
            exit_on_error "Deploy $TF_VAR_deploy_type"
        elif [ "$TF_VAR_deploy_type" == "container_instance" ]; then
            $BIN_DIR/deploy_ci.sh
            exit_on_error "Deploy $TF_VAR_deploy_type"
        fi
        title "Terraform: Export Variables"
        ./starter.sh frm
        EOT
  }
  depends_on = [
    oci_core_instance.starter_compute,
    oci_database_autonomous_database.starter_atp,
    oci_identity_policy.starter_bastion_policy,
    tls_private_key.ssh_key,  
    null_resource.custom_dependency,  
    null_resource.tf_env  
  ]

  triggers = {
    always_run = "${timestamp()}"
  }      
}

## AFTER_BUILD
# Last action at the end of the build
resource "null_resource" "after_build" {
  provisioner "local-exec" {
    command = <<-EOT
        cd ${local.project_dir}    
        export CALLED_BY_TERRAFORM="true"        
        . ./starter.sh env    
        if [ "$TF_VAR_tls" != "" ]; then
            title "Certificate - Post Deploy"
            certificate_post_deploy 
        fi

        $BIN_DIR/add_api_portal.sh

        title "Done"
        $PROJECT_DIR/src/done.sh          
        EOT
  }
  depends_on = [      
    null_resource.build_deploy
  ]

  triggers = {
    always_run = "${timestamp()}"
  }    
}

data "local_file" "done_txt" {
  filename = "${local.project_dir}/target/done.txt"
  depends_on = [
    null_resource.after_build
  ]
}

# OUTPUT done.txt
output "done" {
    value = data.local_file.done_txt.content
}

# BEFORE_DESTROY
resource "null_resource" "before_destroy" {
  provisioner "local-exec" {
      when = destroy
      command = <<-EOT
        if [ ! -f starter.sh ]; then 
          cd ../..
        fi
        ./starter.sh destroy --called_by_resource_manager
        EOT
  }

  depends_on = [  
    null_resource.after_build
  ]
}